# Build Dynamo using latest VS and DotNET
name: DynamoAllNet6.0-Build
on: [push,pull_request]
jobs:
 build:
  runs-on: windows-latest
  steps:
    - name: Checkout Dynamo Repo
      uses: actions/checkout@v4
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Disable problem matcher
      run: echo "::remove-matcher owner=csc::"

    - name: Install dependencies for windows runtime
      run: |
        dotnet restore $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln /p:Configuration=Release --runtime=win10-x64
    - name: Build Dynamo with MSBuild for Windows
      run: |
        echo "***Continue with the build, Good luck developer!***"
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln  /p:Configuration=Release
    # look for Dynamo
    - name: Navigate to Dynamo Windows Folder
      run: |
        cd "$Env:GITHUB_WORKSPACE\Dynamo\bin\AnyCPU\Release"
        echo "***Locating DynamoCLI for Windows!***"
        test ".\DynamoCLI.exe" && echo "DynamoCLI exists!"
    - name: Set artifact name
      run: |
        if ("${{ github.event_name }}" -eq 'pull_request') {
          echo "ARTIFACT_NAME=DynamoSandbox-${{ github.event.pull_request.number }}" >> $env:GITHUB_ENV
        } else {
          echo "ARTIFACT_NAME=DynamoSandbox-$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
        }
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}\Dynamo\bin\AnyCPU\Release
        if-no-files-found: warn
        retention-days: 3
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.DYNAMO_TESTS_TOKEN }}
        repository: DynamoDS/TestCompleteTests
        event-type: build-completed
        client-payload: '{"artifact_name": "${{ env.ARTIFACT_NAME }}"}'
